/**
 * Creates an object with keys generated by running the provided function for each key and the same values as the provided object.
 *
 * @param {{}} obj
 * @param {Function} fn
 */
declare const mapKeys: (obj: {}, fn: Function) => {};
export default mapKeys;
