/**
 * Creates an object with the same keys as the provided object and values generated by running the provided function for each value.
 *
 * @param {{}} obj
 * @param {Function} fn
 */
declare const mapValues: (obj: {}, fn: Function) => {};
export default mapValues;
